language: python
python:
- '2.7'
- '3.6'
script:
- pytest
deploy:
  provider: pypi
  skip_existing: true
  user: 2xB
  password:
    secure: laeotxzKw88oIlyJbxY/oT0AcaRmgXI/ZIuhcZAkU0tjHqek3w9kBjCHQGsaMA8X3HMs/Msi10XvvV6WMKU1E0YmVEHfzraCf01u3rJlEYjW/X1vxgTO+Vm/W0MB0CE5H054QwCYEALeaqMqgk+e9SfCetHsYcepAzAnyuiImm7t9G5zFN2K2+Nlvf4CoUwRZauC6sRHPKtyUVOIVr4d9aYxRS9+BrVwY1+9K+6FcS/PvkFh579MpO600Jco0eFG8UxwLZUa6JG0rld56UDyPmJ23OTA6/RD4+hVXNvehKmhik2H7FRCOyOx5mco+86eXl6HC1og9GLnugDdFgcDqTL5zXjRtA33vQNeDV7KwcCIZswE+ehB2qtqfIOR7d7YXcDDNJk1DyqTpVyZ3Tetb8OUbRYgwHhPvmuAPsaVHUCT4zTZYUBI8yA/Xj6/DMWmrDkrJlerP4VGSRPr6abP+WJWYJ+f2Jm+D9iNPAp9RR+ea4OFXUEbI9aDiVo0t5w+FPJXxXbqq7uAyKgrGHmIt5WtY5z+NXNq8SBKA3tmuxZSjTsrnQgvMNFfDEs6XzvruUlWSHWBJxaJx2ryMx9IS/OyRdIxQ3G44qV3MYfv5nMM0Hx1Kz4TTccuyrb+e5tD9S8nRrEnA+HPH6Kw2lLlEiAXEcJTdRWsLakL7bfs7HY=
  on:
    tags: true
    repo: 2xB/faultguard
