language: python
python:
- '2.7'
- '3.6'
script:
- pytest
deploy:
  provider: pypi
  user: 2xB
  password:
    secure: CxO8mmNj80TFzX86y9QSgiIOvlnJZlvM59PX4zrHTyNiINnRT34PUBOqvtNJXFquivv40T2txF8Qr5+XbCzwCVc6ai8+fntENoj+75I3rPqiyHP34fKd1uTFZM9ZTip48cqbq926NaoM9p582IFVCn0apQEqYLKQehOaANQh1qJ5TH47FAqi2LXJdnsN5BhUYPJCZ5jk3mpA6YzR8fLiJtg81owNU0sEYMl3DOectSQL6a86hRR5Q+oRz8pMVulUpqlIH7mIt1an+HasoFw6BWyDGi1PME8WP6G+9F2lRV1TmBZXe4g3At91kY2ruQK90Pw/nd8vvJDvJhiGRjKToN9KZV7A/7fLYJYClRybVNbX74TNVXtUatuMLLmthaDOP5VB3hTEG6UQZVxTUEoDZod1mQg29EUeAoDfNvdbeX97j5cJi5HpTrTkEoFyMuppbLpE+iVZGZ3WirBgOiLdENx6LEjZ4fplTXzRTUFUDwNpEUbNvq0LXgwh0abCNuomUDrnLcOKd+TUegxk+S4D98S0b6R/mVzJ0V+ECPijl4DlCrO/C8sw4LrFteA6ugelnb5caVCxk+iI7qg2LI/dQ2ptM/v/gPugcgrqvlPMKDDTl3eOorgrQI4AZA1t9aeVrpCqGMogJkOW60BRL5jBj2NOrMUh2Y1u3qyBkr8nrjs=
