language: python
python:
- '2.7'
- '3.6'
script:
- pytest
deploy:
  provider: pypi
  user: 2xB
  password:
    secure: d6QtFHRBJshKRk5cDSywMQJC5S4A3hVI9FxYgqhnbOmI+CjkAXTi0c6YI9ziURx4K+y4SZfSW0Z+Gzlj7U8+E90catbyHpJr0triA1MwWzL0wSXSh9XnghABkmhACXbZNhJS1rceLFzUvvsrO2aJj00P103V/spviWALNnESRnv4bpmUB6uoJYdcFSD0MK8r1gDMhVFfjl4g36TswWml04tOMlnApFava4luoV3rvnoqOZBt/fJAqH8fPPDsX8u2Q96jvG//OXWqwJP+Hs5Y43knQUzPEVHijS+PTieOKF8pci+rBIMFWul58dC2fHxVMDXr57XrEc76oQrc6214rXtQ5gFPzgSPA0P9cZauq5k4K9URL4UoQEqwGSWMWOcLhiiv8FJ2DOdAUJvluF4p52JQ+jsVs+aZUgqzJNHr6/XE4ajjoH+HXHsMsEGCunNbINPMcSrbP91sbGtdz1Dn9ivjyqdiHsZPtMYrZC13lC9gEYnTZqyiPCk5MocIMeexcFjX9PWeQPVk0SFe3uPzS+oVO98D2vS6X4UAHkF3cVv/GaMzxhIJlLbtvNZCoJmoQ8r+AJYa/LjNquIp43UMQC22zcJRjp5qCzeK3KYoZJiKcChn0CF1TGLk08BoVyApugPsZxgGvzIUl+Y+vb29qkXWqav9kDSbkcbmWJ7T6Xg=
  on:
    tags: true
    repo: 2xB/faultguard
