name: Test and publish

on:
  release:
    types: [published]

# The following is based on https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ .
jobs:
  test:
    strategy:
      matrix:
        pyversion: ["3.7", "3.8", "3.9", "3.11"]
        os: [ubuntu-latest, windows-latest]
    name: Test Faultguard using Python ${{ matrix.pyversion }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install requirements
      run: >-
        python -m
        pip install
        pytest
        numpy
        --user
    - name: Run pytest
      run: pytest
  publish:
    name: Publish Faultguard
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TOKEN_PYPI }}
